# Generated by Django 5.2 on 2025-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='issued_by',
        ),
    ]
